name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Insteall Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-none

      - name: Build kernel
        run: cargo build --release